### ISSUE TITLE
How can I execute the sql query to generate the .csv ?

### ISSUE THREAD

**Issue by Athanaze** [Eeysirhc/ergodex-price-app#1]
I have a full ergo node running.
How do I run the sql query ?
Instructions in the README.md would be very much welcome :)

**Comment by Eeysirhc** [comment]
Sounds good - I will come back to this after completion of ErgoHack III but thank you for raising this!

**Comment by Athanaze** [comment]
Hi,
Any news on this ?
(I don't want to sound rude, I am just eager to try your stuff :smile:  )

**Comment by Eeysirhc** [comment]
Sorry for not getting to this sooner!

README.md updated with instructions. I hope this helps but if not please LMK more than happy to help! :)
